# Generated by Django 2.2 on 2021-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_filecomments_userfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
